# Inspired by https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/


stages:
  - docker_build
  - docker_push
  - deploy

Build container:
  stage: docker_build
  only:
    changes:
      - Dockerfile
      - package.json
      - package-lock.json
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VCS_URL=$CI_PROJECT_URL
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $IMAGE_TAG
      .
    - docker push $IMAGE_TAG

Push latest:
  stage: docker_push
  only:
    refs:
      - master
    changes:
      - Dockerfile
      - package.json
      - package-lock.json
  variables:
    GIT_STRATEGY: none
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    IMAGE_NEW_TAG: $CI_REGISTRY_IMAGE:latest
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $IMAGE_NEW_TAG
    - docker push $IMAGE_NEW_TAG

Push tags:
  stage: docker_push
  only:
    refs:
      - tags
    changes:
      - Dockerfile
      - package.json
      - package-lock.json
  variables:
    GIT_STRATEGY: none
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    IMAGE_NEW_TAG: $CI_REGISTRY_IMAGE:CI_COMMIT_REF_NAME
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $IMAGE_NEW_TAG
    - docker push $IMAGE_NEW_TAG

pages:
  stage: deploy
  image: $CI_REGISTRY_IMAGE:latest
  script:
  - npm install --ignore-optional
  - ./node_modules/.bin/bsb -make-world
  - ./node_modules/.bin/webpack --config webpack.production.js --output-path $PWD/public
  - cp public/index.html public/404.html
  artifacts:
    paths:
    - public
  only:
  - master
