FROM node:13 as build-stage


RUN mkdir /home/node/app

WORKDIR /home/node/app

COPY ./package-lock.json ./package.json /home/node/app/

RUN npm install --ignore-optional

ENV PATH=./node_modules/.bin:$PATH

COPY ./ /home/node/app/

RUN npm run build


FROM nginx:1.19

COPY --from=build-stage /home/node/app/dist/ /usr/share/nginx/html

COPY --from=build-stage /home/node/app/nginx.conf /etc/nginx/conf.d/default.conf
