// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Matrix from "./matrix.bs.js";
import * as Tea_cmd from "bucklescript-tea/lib/es6/src-ocaml/tea_cmd.js";
import * as Tea_html from "bucklescript-tea/lib/es6/src-ocaml/tea_html.js";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Tea_promise from "bucklescript-tea/lib/es6/src-ocaml/tea_promise.js";
import * as Caml_chrome_debugger from "bs-platform/lib/es6/caml_chrome_debugger.js";

function login(param_0) {
  return /* Login */Caml_chrome_debugger.variant("Login", 0, [param_0]);
}

function getJoinedRooms(param_0) {
  return /* GetJoinedRooms */Caml_chrome_debugger.variant("GetJoinedRooms", 1, [param_0]);
}

function goTo(param_0) {
  return /* GoTo */Caml_chrome_debugger.variant("GoTo", 2, [param_0]);
}

var client = Matrix.new_client(/* () */0);

var model = /* record */Caml_chrome_debugger.record([
    "client",
    "matrix_id",
    "joined_rooms_ids"
  ], [
    client,
    undefined,
    0
  ]);

var cmd = Tea_promise.result(Matrix.login(client), login);

var init = /* tuple */[
  model,
  cmd
];

function update(model, param) {
  switch (param.tag | 0) {
    case 0 : 
        var match = param[0];
        if (match.tag) {
          console.log(match[0]);
          return /* tuple */[
                  model,
                  Tea_cmd.none
                ];
        } else {
          var res = match[0];
          console.log(res);
          var model_000 = /* client */model[/* client */0];
          var model_001 = /* matrix_id */res.user_id;
          var model_002 = /* joined_rooms_ids */model[/* joined_rooms_ids */2];
          var model$1 = /* record */Caml_chrome_debugger.record([
              "client",
              "matrix_id",
              "joined_rooms_ids"
            ], [
              model_000,
              model_001,
              model_002
            ]);
          var cmd = Tea_promise.result(Matrix.get_joined_rooms(model_000), getJoinedRooms);
          return /* tuple */[
                  model$1,
                  cmd
                ];
        }
    case 1 : 
        var match$1 = param[0];
        if (match$1.tag) {
          console.log(match$1[0]);
          return /* tuple */[
                  model,
                  Tea_cmd.none
                ];
        } else {
          var res$1 = match$1[0];
          console.log(res$1);
          var model_000$1 = /* client */model[/* client */0];
          var model_001$1 = /* matrix_id */model[/* matrix_id */1];
          var model$2 = /* record */Caml_chrome_debugger.record([
              "client",
              "matrix_id",
              "joined_rooms_ids"
            ], [
              model_000$1,
              model_001$1,
              res$1
            ]);
          return /* tuple */[
                  model$2,
                  Tea_cmd.none
                ];
        }
    case 2 : 
        return /* tuple */[
                model,
                Tea_cmd.none
              ];
    
  }
}

function room_list_view(model) {
  return Tea_html.ul(undefined, undefined, /* [] */0, Belt_List.map(model[/* joined_rooms_ids */2], (function (room_id) {
                    return Tea_html.li(undefined, undefined, /* [] */0, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                  Tea_html.button(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          Tea_html.onClick(/* GoTo */Caml_chrome_debugger.variant("GoTo", 2, [/* Room */Caml_chrome_debugger.simpleVariant("Room", [room_id])])),
                                          /* [] */0
                                        ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                          Tea_html.text(room_id),
                                          /* [] */0
                                        ])),
                                  /* [] */0
                                ]));
                  })));
}

export {
  login ,
  getJoinedRooms ,
  goTo ,
  init ,
  update ,
  room_list_view ,
  
}
/* client Not a pure module */
