// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Matrix from "./matrix.bs.js";
import * as Tea_app from "bucklescript-tea/src-ocaml/tea_app.js";
import * as Tea_cmd from "bucklescript-tea/src-ocaml/tea_cmd.js";
import * as Tea_sub from "bucklescript-tea/src-ocaml/tea_sub.js";
import * as Tea_html from "bucklescript-tea/src-ocaml/tea_html.js";
import * as Tea_promise from "bucklescript-tea/src-ocaml/tea_promise.js";
import * as Caml_chrome_debugger from "bs-platform/lib/es6/caml_chrome_debugger.js";

function login(param_0) {
  return /* Login */Caml_chrome_debugger.variant("Login", 0, [param_0]);
}

function set(param_0) {
  return /* Set */Caml_chrome_debugger.variant("Set", 1, [param_0]);
}

function init(param) {
  console.log("init");
  var client = Matrix.new_client(/* () */0);
  return /* tuple */[
          /* record */Caml_chrome_debugger.record(["client"], [client]),
          Tea_promise.result(Matrix.login(client), login)
        ];
}

function update(model, param) {
  if (typeof param === "number" || param.tag) {
    return /* tuple */[
            model,
            Tea_cmd.none
          ];
  } else {
    console.log(param[0][0]);
    return /* tuple */[
            model,
            Tea_cmd.none
          ];
  }
}

function view_button(title, msg) {
  return Tea_html.button(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.onClick(msg),
                /* [] */0
              ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.text(title),
                /* [] */0
              ]));
}

function view(model) {
  return Tea_html.div(undefined, undefined, /* [] */0, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                Tea_html.span(undefined, undefined, /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.style("text-weight", "bold"),
                        /* [] */0
                      ]), /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        Tea_html.text("lol"),
                        /* [] */0
                      ])),
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    Tea_html.br(/* [] */0),
                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                        view_button("Increment", /* Increment */0),
                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                            Tea_html.br(/* [] */0),
                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                view_button("Decrement", /* Decrement */1),
                                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                    Tea_html.br(/* [] */0),
                                    /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                        view_button("Set to 2", /* Set */Caml_chrome_debugger.variant("Set", 1, [42])),
                                        /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                            Tea_html.br(/* [] */0),
                                            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                                                Tea_html.noNode,
                                                /* [] */0
                                              ])
                                          ])
                                      ])
                                  ])
                              ])
                          ])
                      ])
                  ])
              ]));
}

function partial_arg_003(param) {
  return Tea_sub.none;
}

var partial_arg = /* record */Caml_chrome_debugger.record([
    "init",
    "update",
    "view",
    "subscriptions"
  ], [
    init,
    update,
    view,
    partial_arg_003
  ]);

function main(param, param$1) {
  return Tea_app.standardProgram(partial_arg, param, param$1);
}

var increment = /* Increment */0;

var decrement = /* Decrement */1;

var reset = /* Reset */2;

export {
  login ,
  increment ,
  decrement ,
  reset ,
  set ,
  init ,
  update ,
  view_button ,
  view ,
  main ,
  
}
/* Matrix Not a pure module */
