// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as App from "./app.bs.js";
import * as Web_document from "bucklescript-tea/lib/es6/src-ocaml/web_document.js";

setTimeout((function (param) {
        App.main(Web_document.getElementById("my-element"), /* () */0);
        return /* () */0;
      }), 0);

export {
  
}
/*  Not a pure module */
