// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as MatrixJsSdk from "matrix-js-sdk";

function get_joined_rooms(client) {
  return client.getJoinedRooms().then((function (res) {
                return Promise.resolve(res.joined_rooms);
              }));
}

function new_client(param) {
  return MatrixJsSdk.createClient("https://imago-dev.img:8448");
}

function login(client) {
  var login_map = { };
  login_map["user"] = "alice";
  login_map["password"] = "imago42imago";
  return client.login("m.login.password", login_map);
}

function add(a, b) {
  return a + b | 0;
}

export {
  get_joined_rooms ,
  new_client ,
  login ,
  add ,
  
}
/* matrix-js-sdk Not a pure module */
