// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Tablecloth from "tablecloth-bucklescript/lib/es6/src/tablecloth.bs.js";
import * as MatrixJsSdk from "matrix-js-sdk";

function get_joined_rooms(client) {
  return client.getJoinedRooms().then((function (res) {
                return Promise.resolve(Tablecloth.$$Array[/* to_list */11](res.joined_rooms));
              }));
}

function new_client(param) {
  return MatrixJsSdk.createClient("https://imago-dev.img:8448");
}

function new_client_params(matrix_id, access_token) {
  var login_map = { };
  login_map["baseUrl"] = "https://imago-dev.img:8448";
  login_map["accessToken"] = access_token;
  login_map["userId"] = matrix_id;
  return MatrixJsSdk.createClient(login_map);
}

function login(client) {
  var login_map = { };
  login_map["user"] = "alice";
  login_map["password"] = "imago42imago";
  return client.login("m.login.password", login_map);
}

function login_with_token(client, token) {
  return client.loginWithToken(token);
}

export {
  get_joined_rooms ,
  new_client ,
  new_client_params ,
  login ,
  login_with_token ,
  
}
/* Tablecloth Not a pure module */
