// Generated by BUCKLESCRIPT VERSION 6.0.3, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Tea_sub from "bucklescript-tea/lib/es6/src-ocaml/tea_sub.js";
import * as Tablecloth from "tablecloth-bucklescript/lib/es6/src/tablecloth.bs.js";
import * as MatrixJsSdk from "matrix-js-sdk";
import * as Caml_chrome_debugger from "bs-platform/lib/es6/caml_chrome_debugger.js";

function get_joined_rooms(client) {
  return client.getJoinedRooms().then((function (res) {
                return Promise.resolve(Tablecloth.$$Array[/* to_list */11](res.joined_rooms));
              }));
}

function subscribe(client, tagger) {
  var enableCall = function (callbacks) {
    var args_001 = function ($$event, _room, _toStartOfTimeline, _removed, _data) {
      return Curry._1(callbacks[/* enqueue */0], Curry._1(tagger, $$event));
    };
    client.on((function () {
              switch (-46436735) {
                case -46436735 : 
                    return "Room.timeline";
                
              }
            })(), args_001);
    return (function (param) {
        client.off((function () {
                  switch (-46436735) {
                    case -46436735 : 
                        return "Room.timeline";
                    
                  }
                })(), args_001);
        return /* () */0;
      });
  };
  return Tea_sub.registration("test", enableCall);
}

function subscribe_once(client, tagger) {
  var enableCall = function (callbacks) {
    var args_001 = function (state, _prevState, _data) {
      return Curry._1(callbacks[/* enqueue */0], Curry._1(tagger, state));
    };
    client.once((function () {
              switch (-866141605) {
                case -866141605 : 
                    return "sync";
                
              }
            })(), args_001);
    return (function (param) {
        return /* () */0;
      });
  };
  return Tea_sub.registration("sync", enableCall);
}

function new_client(param) {
  return MatrixJsSdk.createClient("https://imago-dev.img:8448");
}

function new_client_params(matrix_id, access_token) {
  var login_map = { };
  login_map["baseUrl"] = "https://imago-dev.img:8448";
  login_map["accessToken"] = access_token;
  login_map["userId"] = matrix_id;
  return MatrixJsSdk.createClient(login_map);
}

function login(client) {
  var login_map = { };
  login_map["user"] = "alice";
  login_map["password"] = "imago42imago";
  return client.login("m.login.password", login_map);
}

export {
  get_joined_rooms ,
  subscribe ,
  subscribe_once ,
  new_client ,
  new_client_params ,
  login ,
  
}
/* Tablecloth Not a pure module */
