// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Plugin = require("../src/plugin.bs.js");

var partial_arg = ["./test/en.ftl"];

function test(param) {
  return $$Plugin.process_files(partial_arg, "./test_output.ml", param);
}

exports.test = test;
/* Plugin Not a pure module */
