// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Plugin = require("../src/plugin.bs.js");

var test = $$Plugin.process_files(["./test/en.ftl"], "./test_output.ml");

exports.test = test;
/* test Not a pure module */
