// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Plugin = require("../src/plugin.bs.js");

$$Plugin.process_files(["./test/en.ftl"], "./test_output.ml", "en", null);

/*  Not a pure module */
