// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function number_format(n, params, lc) {
  var nf = new Intl.NumberFormat(lc, params);
  return nf.format(n);
}

function plural_rule(n, _typeOpt, lc) {
  var _type = _typeOpt !== undefined ? _typeOpt : "cardinal";
  var params = {
    type: _type
  };
  var pr = new Intl.PluralRules(lc, params);
  return pr.select(n);
}

function datetime_format(d, params, lc) {
  var dtf = new Intl.DateTimeFormat(lc, params);
  return dtf.format(d);
}

var Runtime;

exports.Runtime = Runtime;
exports.number_format = number_format;
exports.plural_rule = plural_rule;
exports.datetime_format = datetime_format;
/* No side effect */
