// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var Compiler = require("./compiler.bs.js");
var FluentSyntax = require("fluent-syntax");

function process_files(source, dest) {
  var file_path = source[0];
  var parser = new FluentSyntax.FluentParser();
  var absolute_path = Path.resolve(file_path);
  var content = Fs.readFileSync(absolute_path, ({"encoding": "utf-8"}));
  var ast = parser.parse(content);
  var output = Compiler.compile("en", ast);
  Fs.writeFileSync(dest, output);
  
}

exports.process_files = process_files;
/* fs Not a pure module */
